### ISSUE TITLE
clock_gettime missing in GCC/MinGW-w64 build with mcfgthread

### ISSUE THREAD

**Issue by brechtsanders** [lhmouse/MINGW-packages#11]
I have been testing GCC+MinGW-w64 built with mcfgthread (specifically [this build](https://github.com/brechtsanders/winlibs_mingw/releases/tag/13.0.1-snapshot20230402-11.0.0-ucrt-r1)) by building a lot of stuff from source with it.

Several projects fail to build because `clock_gettime` seems to be missing.

This is present in MinGW-w64 when built with pthread.

**Comment by lhmouse** [comment]
To be honest, I was aware of that. This function is provided by winpthreads and does not exist in the CRT. However, I don't think mcfgthread should implement this function, not only because it has nothing to do with threading, but also because it could conflict if winpthreads also gets linked.

Maybe I can copy the implementation into the CRT, but it can hardly be upstreamed.

**Comment by lhmouse** [comment]
It should be fixed by this. I will include this patch once GCC 13.1 is released.

https://github.com/lhmouse/MINGW-packages/blob/master/mingw-w64-crt-git/9004-crt-Copy-clock-and-nanosleep-from-winpthreads.patch

**Comment by lhmouse** [comment]
It should be fixed now.

**Comment by lhmouse** [comment]
https://gcc-mcf.lhmouse.com/mingw-w64-gcc-mcf_20230426_13.1.0_x64-ucrt_28671da60cf119b09b801ccdf46e14d7dfed2d6e.7z

**Comment by brechtsanders** [comment]
GCC 13 has been released. It's a shame MinGW-w64 didn't release a new version recently (given the fact that several issues have been fixed in MinGW-w64).

**Comment by lhmouse** [comment]
A new release may be coming soon. Maybe.

**Comment by lhmouse** [comment]
Should this be closed?

**Comment by brechtsanders** [comment]
Yes, sure.
I see the new MinGW-w64 release is out, I'm already making the native builds.
Thanks!
